version: "3.8"
services:
   postgres_cadastro:
      container_name: postgres_cadastro
      image: postgres:12.2
      environment: 
         POSTGRES_USER: cadastro
         PORTGRES_PASSWORD: cadastro
         POSTGRES_HOST_AUTH_METHOD: trust
      ports:
         - "5432:5432"
   postgres_marketplace:
      container_name: postgres_marketplace
      image: postgres:12.2
      environment: 
         POSTGRES_USER: marketplace
         PORTGRES_PASSWORD: marketplace
         POSTGRES_HOST_AUTH_METHOD: trust
      ports:
         - "5433:5432"
   keycloak_projeto:
       container_name: keycloak_projeto
       image: jboss/keycloak:9.0.2
       environment: 
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: admin
       ports:
         - "8180:8080"        
   jaeger_projeto:
       container_name: jaeger_projeto
       image: jaegertracing/all-in-one:1.18
       ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "14250:14250"
          - "9411:9411"
   prometheus_projeto:
      container_name: prometheus_projeto
      image: prometheus-projeto
      network_mode: "host"
      
   grafana_projeto:
      container_name: grafana_projeto
      image: grafana/grafana
      network_mode: "host"

   artemis_projeto:
      container_name: artemis_projeto
      image: vromero/activemq-artemis:latest
      network_mode: "host"
      environment: 
         ARTEMIS_USERNAME: admin
         ARTEMIS_PASSWORD: admin
   mongodb_projeto:
      container_name: mongo_projeto_pedido
      image: mongo:4.2.5-bionic
      ports:
         - "27017:27017"
      environment: 
         MONGO_INITDB_ROOT_USERNAME: pedido
         MONGO_INITDB_ROOT_PASSWORD: pedido
         MONGO_INITDB_DATABASE: pedido
       
   zookeeper:
    container_name: zookeeper_container
    image: debezium/zookeeper:1.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
   kafka:
    container_name: kafka_container
    image: debezium/kafka:1.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     
   kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
       KAFKA_BROKERCONNECT: kafka:9092
    ports:
     - 9000:9000
    depends_on:
      - kafka
      
        
       