version: "3.8"
services:
   postgres_cadastro:
      container_name: postgres_cadastro
      image: postgres:12.2
      environment: 
         POSTGRES_USER: cadastro
         PORTGRES_PASSWORD: cadastro
         POSTGRES_HOST_AUTH_METHOD: trust
      ports:
         - "5432:5432"
   keycloak_projeto:
       container_name: keycloak_projeto
       image: jboss/keycloak:9.0.2
       environment: 
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: admin
       ports:
         - "8180:8080"        
   jaeger_projeto:
       container_name: jaeger_projeto
       image: jaegertracing/all-in-one:1.18
       ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "14250:14250"
          - "9411:9411"
   prometheus_projeto:
      container_name: prometheus_projeto
      image: prometheus-projeto
      network_mode: "host"
      
   grafana_projeto:
      container_name: grafana_projeto
      image: grafana/grafana
      network_mode: "host"

       
       

       